version: "3"
services:
  monitor:
    image: zongzw/monitoring-ts-lb4:latest
    container_name: MONITOR
    ports:
     - 8085:3000
    environment:
      - INFLUXDB_URL=http://influxdb-server:8086
    links:
     - influxdb:influxdb-server

  influxdb:
    image: influxdb:latest
    container_name: INFLUXDB
    environment:
     - INFLUXDB_DB=mydb
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
     - 8086:8086
    volumes:
     - ${ROOTDIR}/data/influx:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: GRAFANA
    links:
      - influxdb:influxdb-server
    ports:
      - 8087:3000
    user: "472"
    volumes:
      - ${ROOTDIR}/data/grafana:/var/lib/grafana
